name: Fetch YouBike Snapshot

on:
  schedule:
    - cron: '*/5 * * * *'            # 每 5 分鐘（UTC）
  workflow_dispatch:                 # 手動測試用

concurrency:
  group: snapshot-${{ github.ref }}  # 防止重疊，分支區分
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  fetch:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data-log branch
        uses: actions/checkout@v4
        with:
          ref: data-log

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run snapshot script
        run: python fetch_snapshot.py

      - name: Commit & push if data changed
        run: |
          git config --global user.name  "youbike-bot"
          git config --global user.email "bot@example.com"

          git add data/
          if git diff --cached --quiet; then
            echo "No changes – skip commit"
            exit 0
          fi

          # 使用台灣時間
          COMMIT_TIME=$(TZ='Asia/Taipei' date '+%Y-%m-%d %H:%M')
          git commit -m "Snapshot $COMMIT_TIME"

          # 嘗試 rebase 最新遠端變更以避免 push 衝突
          git pull --rebase origin data-log || {
            echo "❌ Rebase failed. Aborting push."
            git rebase --abort
            exit 1
          }

          git push origin HEAD:data-log
