name: Fetch YouBike Snapshot

# 1. 只在主分支，2. 從 5/23 起，3. 每 5 分鐘
on:
  schedule:
    - cron: '*/5 * * * *'            # GitHub 以 UTC 解讀
  workflow_dispatch:                 # 手動觸發方便測試
concurrency: snapshot                # 防止重疊執行

permissions:
  contents: write                    # 允許 push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run snapshot script
        run: python fetch_snapshot.py

      - name: Commit & push if data changed
        run: |
          git add data/
          if git diff --cached --quiet; then
            echo "No changes – skip commit"
            exit 0
          fi
          git config --global user.name  "youbike-bot"
          git config --global user.email "bot@example.com"
          git commit -m "Snapshot $(date -u '+%Y-%m-%d %H:%M')"
          git push
